// Autogenerated from Pigeon (v14.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "NotificationApi.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface NotificationMessage ()
+ (NotificationMessage *)fromList:(NSArray *)list;
+ (nullable NotificationMessage *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation NotificationMessage
+ (instancetype)makeWithId:(nullable NSNumber *)id
    title:(nullable NSString *)title
    body:(nullable NSString *)body
    scheduleTime:(nullable NSNumber *)scheduleTime {
  NotificationMessage* pigeonResult = [[NotificationMessage alloc] init];
  pigeonResult.id = id;
  pigeonResult.title = title;
  pigeonResult.body = body;
  pigeonResult.scheduleTime = scheduleTime;
  return pigeonResult;
}
+ (NotificationMessage *)fromList:(NSArray *)list {
  NotificationMessage *pigeonResult = [[NotificationMessage alloc] init];
  pigeonResult.id = GetNullableObjectAtIndex(list, 0);
  pigeonResult.title = GetNullableObjectAtIndex(list, 1);
  pigeonResult.body = GetNullableObjectAtIndex(list, 2);
  pigeonResult.scheduleTime = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable NotificationMessage *)nullableFromList:(NSArray *)list {
  return (list) ? [NotificationMessage fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    self.id ?: [NSNull null],
    self.title ?: [NSNull null],
    self.body ?: [NSNull null],
    self.scheduleTime ?: [NSNull null],
  ];
}
@end

@interface NotificationApiCodecReader : FlutterStandardReader
@end
@implementation NotificationApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [NotificationMessage fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface NotificationApiCodecWriter : FlutterStandardWriter
@end
@implementation NotificationApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[NotificationMessage class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface NotificationApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation NotificationApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[NotificationApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[NotificationApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *NotificationApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    NotificationApiCodecReaderWriter *readerWriter = [[NotificationApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void SetUpNotificationApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<NotificationApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.assessment.NotificationApi.sendNotification"
        binaryMessenger:binaryMessenger
        codec:NotificationApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(sendNotificationMessage:error:)], @"NotificationApi api (%@) doesn't respond to @selector(sendNotificationMessage:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NotificationMessage *arg_message = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api sendNotificationMessage:arg_message error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.assessment.NotificationApi.scheduleNotification"
        binaryMessenger:binaryMessenger
        codec:NotificationApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(scheduleNotificationMessage:error:)], @"NotificationApi api (%@) doesn't respond to @selector(scheduleNotificationMessage:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NotificationMessage *arg_message = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        [api scheduleNotificationMessage:arg_message error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
